### PR TITLE
Make script Python executable

### PR DESCRIPTION
**Pull request by amaltson**
This PR turns the `safaribooks.py` script running into a full fledged CLI that can be `pip` installed and runs with `safaribooks` sans the `.py` at the end.

I needed to:
- Turn this into a Python module.
- Introduce `setup.py` to make it installable.
- Refactor the location of the CLI code into a callable method.
- Updated docs with the new way to run it.

This also helps start moving towards refactoring, adding tests, etc as this becomes a Python module.

### CODE REVIEW

**Comment by lorenzodifuccia** [comment]
Could you try to merge with #137?

**Comment by amaltson** [comment]
That PR just makes the Python script executable, this is a larger change to make it `pip` installable.

**Comment by amaltson** [comment]
@lorenzodifuccia so it looks like a whooole bunch of code changed in the past couple weeks and it'll take some time to merge that code back in.

Are you still interested in this change? If so, I'll take the time to re-build what I did with the latest code base. Thanks!

**Comment by lorenzodifuccia** [comment]
Closing this PR because old. If you want, adapt your changes to the new version of the code and create another PR.
Cheers 🍻

**Pull request closed without merging**
