### PR TITLE
Update BASE_URL to learning.oreilly.com

### PR DESCRIPTION
**Pull request by pnhoang**
This PR update the BASE_URL to the new URL and also set the values for checking cookies correctly.

### CODE REVIEW

**Comment by nguyendat** [comment]
Tested, work life a charm

**Comment by volkan** [comment]
I Tested, it is working. Thanks.

**Comment by vigo** [comment]
Yeah It works!

**Comment by roboserg** [comment]
yep, it works

**Comment by linux0x5c** [comment]
# I had update it,but have some error for it.

[-] Logging into Safari Books Online...                                                                                                                    
[*] Retrieving book info...                                                                                                                                
[#] API: Out-of-Session (Authentication credentials were not provided.).                                                                                   

[+] Please delete all the `<BOOK NAME>/OEBPS/*.xhtml` files and restart the program.

**Comment by dexter101010** [comment]
Does not work anymore....

**Comment by roboserg** [comment]
> Does not work anymore....

It still works, just checked.

**Comment by dexter101010** [comment]
I don't know how it works for you but here it give me the error with missing json cookies. Even with updated script from 65#

**Comment by dexter101010** [comment]
I don't know how it works for you but here it give me the error with missing json cookies. Even with updated script from 65#

[-] Logging into Safari Books Online...
[*] Retrieving book info...
[#] Unhandled Exception: [WinError 2] The system cannot find the file specified: 'C:\Users\XYZ\safaribooks\cookies.json' (type: FileNotFoundError)
[+] Please delete all the <BOOK NAME>/OEBPS/*.xhtml files and restart the program.
[!] Aborting...

**Comment by roboserg** [comment]
This PR is #54, not #65 or am I missing something?

**Comment by dexter101010** [comment]
No, you are right. Updated to 54 and i get same error.

**Comment by linux0x5c** [comment]
@dexter101010 I have same problem with you,did you solved it?

**Comment by pnhoang** [comment]
Hey, it's still working fine for me on this PR, maybe you have to check how to use the script in the readme. how did you use it?

**Comment by arulk** [comment]
After applying the changes, the formatting of epub created is messed up. There seems to be a gray box behind most of the book text. Anyone else experiencing this ?

**Comment by lorenzodifuccia** [comment]
Thank you for this PR. I pushed a new version (622529b) that includes your changes.
Thanks all for the support! :heart:

**Pull request closed without merging**
