### PR TITLE
Set body background color to transparent

### LINKED ISSUE #63: Body background color slows down my ebook reader
The script adds a style tag to every chapter page that sets the background of the body element. Having a background color on every page slows down and breaks the refresh of my Kobo ebook reader.

To remove the background color I changed line 211 from
`"body{{background-color:#fbfbfb!important;margin:1em;}}" \`
To:
`"body{{background-color:transparent!important;margin:1em;}}" \`

This fixed the issue for me, but I would like to ask why you were setting a background color to the body in the first place. 

If you agree that we don't actually need a body background color, I submitted a PR that you can merge :)

### PR DESCRIPTION
**Pull request by fedme**
Fixes #63

### CODE REVIEW

**Comment by lorenzodifuccia** [comment]
Thanks @fdmnio.
I honesty don't remember why I set these value. I saw that the default value of `background-color` is already `transparent`. So let's remove directly the role `background-color` so it will no interfere with book style sheets.
What you think about?

**Comment by fdmnio** [comment]
> So let's remove directly the rule `background-color` so it will not interfere with book style sheets.
> What do you think about?

I tried removing it but the book I was trying to convert had a gray background, so I think it's a good idea to force the transparent background this way.

**Comment by lorenzodifuccia** [comment]
Ok, but let's move this CSS rule to the Kindle section (`KINDLE_HTML`), because without the `--kindle` flag maybe someone would like to see original background color.

**Comment by lorenzodifuccia** [comment]
Closed with the commit c33d6f7:
- removed the CSS `background-color` directive on the BASE_01_HTML
- added a CSS directive for the KINDLE_HTML.

When you download a book without the `--kindle` flag it shows the background defined by the book's CSS. Instead, you will have a transparent background on kindle format of the ebook.

**Pull request closed without merging**
